# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='capacity',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_time',
        ),
    ]
