# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190425_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bus',
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='destination_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BusOrganisation'),
        ),
    ]
