# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190429_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
