# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190429_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
